name: Docs Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker tags
        id: meta
        run: |
          version_tag="${{github.ref_name}}"
          tags=($version_tag)
          if [[ "$version_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            tags+=("latest")
          fi
          releases=""
          for tag in "${tags[@]}"; do
            releases="${releases:+$releases,}${{ secrets.DOCKERHUB_USERNAME }}/mafl:$tag"
          done
          echo "releases=$releases" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./docs
          file: ./docs/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.releases }}
